name: Dev Container CI

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"
permissions:
  contents: write
  packages: write

jobs:
  build:
    strategy:
      matrix:
        platform:
          - arm64
          - armhf
          - armel
          - riscv64
          - amd64
          - i386
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Dev Container
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/${{ github.repository_owner }}/armhf_cross_compile/devcontainer
          cacheFrom: ghcr.io/${{ github.repository_owner }}/armhf_cross_compile/devcontainer
          runCmd: |
            if [ "${{ matrix.platform }}" == "arm64" ]; then
            export CROSS_ARCH=${{ matrix.platform }}
            export CC=aarch64-linux-gnu-gcc
            export CPP=aarch64-linux-gnu-g++
            elif [ "${{ matrix.platform }}" == "armhf" ]; then
            export CROSS_ARCH=${{ matrix.platform }}
            export CC=arm-linux-gnueabihf-gcc
            export CPP=arm-linux-gnueabihf-g++
            elif [ "${{ matrix.platform }}" == "armel" ]; then
            export CROSS_ARCH=${{ matrix.platform }}
            export CC=arm-linux-gnueabi-gcc
            export CPP=arm-linux-gnueabi-g++
            elif [ "${{ matrix.platform }}" == "riscv64" ]; then
            export CROSS_ARCH=${{ matrix.platform }}
            export CC=riscv64-linux-gnu-gcc
            export CPP=riscv64-linux-gnu-g++
            elif [ "${{ matrix.platform }}" == "amd64" ]; then
            export CROSS_ARCH=${{ matrix.platform }}
            export CC=x86_64-linux-gnu-gcc
            export CPP=x86_64-linux-gnu-g++
            elif [ "${{ matrix.platform }}" == "i386" ]; then
            export CROSS_ARCH=${{ matrix.platform }}
            export CC=i686-linux-gnu-gcc
            export CPP=i686-linux-gnu-g++
            fi
            make cross_compile
            
      - name: Upload files to GH release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: firmware_${{ matrix.platform }}.bin
          asset_name: firmware_${{ matrix.platform }}_${{ github.ref }}.bin
          prerelease: true